import { AppBar } from '@/components/AppBar';
import { Sidebar } from '@/components/Sidebar';
import AuthProvider from '@/context/AuthProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <AuthProvider>
                    <div className='flex'>
                        <Sidebar />
                        <AppBar />
                    </div>
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
